### ISSUE TITLE
Import von Nextcloud-Ical in The Events Calendar

### ISSUE THREAD

**Issue by alex0107** [kartevonmorgen/wp-kvm-syndication-toolbox#13]
Hi Sjoerd,

wir haben folgenden Fehler beim Import eines Nextcloud-Ical:

Fatal error: Uncaught Error: Call to a member function has_error() on null in httpdocs/wp-content/plugins/wp-kvm-syndication-toolbox-main/modules/wp-events-feed-importer/admin/inc/models/class-ss-defaulteventprocessor.php:57 Stack trace: #0 httpdocs/wp-content/plugins/wp-kvm-syndication-toolbox-main/modules/wp-events-feed-importer/admin/inc/models/class-ss-abstractimport.php(392): SSDefaultEventProcessor->process() #1 httpdocs/wp-content/plugins/wp-kvm-syndication-toolbox-main/modules/wp-events-feed-importer/inc/lib/feed/class-ss-updatefeed.php(17): SSAbstractImport->import() #2 httpdocs/wp-content/plugins/wp-kvm-syndication-toolbox-main/inc/lib/ui/class-ui-posttableaction.php(162): SSUpdateFeed->action() #3 httpdocs/wp-includes/class-wp-hook.php(310): UIPostTableAction->do_action() #4 httpdocs/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters() #5 httpdocs/wp-includes/plugin.php(517): WP_Hook->do_action() #6 httpdocs/wp-admin/admin.php(259): do_action() #7 httpdocs/wp-admin/edit.php(10): require_once('...') #8 {main} thrown in httpdocs/wp-content/plugins/wp-kvm-syndication-toolbox-main/modules/wp-events-feed-importer/admin/inc/models/class-ss-defaulteventprocessor.php on line 57

**Comment by sjoerdtakken** [comment]
@alex0107 Would you like me to offer a URL of the Nextcloud-Ical Feed, so I can reproduce the error.

Greetings,
Sjoerd
