### ISSUE TITLE
Cron not working / No automatic update

### ISSUE THREAD

**Issue by alex0107** [kartevonmorgen/wp-kvm-syndication-toolbox#14]
Hi :)

the automatic update not working. I've made the screenshot today :)
Can you please fix it?

This screenshot is from the event-feed-update:
<img width="1404" alt="Bildschirmfoto 2023-09-11 um 08 02 59" src="https://github.com/kartevonmorgen/wp-kvm-syndication-toolbox/assets/17063865/ca3f5c57-8a27-4c80-8b45-2b676e58a22a">

and the registered cronjobs:
<img width="2370" alt="image" src="https://github.com/kartevonmorgen/wp-kvm-syndication-toolbox/assets/17063865/b9bf239b-2e83-409b-9264-acce61127da6">

Thank you
Alex

**Comment by alex0107** [comment]
@wellemut Who can fix this??

**Comment by sjoerdtakken** [comment]
@alex0107 I fixed this Issue and installed an update on Marburg von Morgen and habe tested the Cron Task, this works now wenn I activite it manuelly. Automatically it is still not working because in wp-config.php DISABLE_WP_CRON is set on true. Is there a reason for it ?
